version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: deps
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:35"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(docker)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:50"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(actions)
    groups:
      github-actions:
        patterns:
          - "*"
